mod collections;
mod common_programming_concepts;
mod enums_and_pattern_matching;
mod guess_the_number;
mod structs;
mod understanding_ownership;
//use guess_the_number::guess_game;
//use common_programming_concepts::variables_mutability::variables;
//use common_programming_concepts::control_flow::functions;
//use common_programming_concepts::control_flow::loops;
//use understanding_ownership::ownership;
//use understanding_ownership::slices;
//use structs::structs::structs;
//use structs::methods;
//use enums_and_pattern_matching::enums_in_rust::enums;
//use enums_and_pattern_matching::pattern_matching;
//use collections::common_collections;
fn main() {
    //guess_game();
    //variables();
    //   functions();
    //   loops();
    //   ownership::ownership_fun();
    //slices::slices_in_rust();
    //structs();
    //   methods::methods();
    //   enums();
    //pattern_matching::matching();
    //common_collections::vector_collections();
    //common_collections::string_collections();
}
